# Generated by Django 4.0.4 on 2022-05-26 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_comment_name_comment_text_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='user_id',
        ),
    ]
