# Generated by Django 4.0.4 on 2022-05-26 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_user_comment_usr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='usr',
            new_name='user',
        ),
    ]
